version: '3.8'
services:
  db:
    image: immanewbies/muse-mysql:latest
    environment:
      MYSQL_USER: "new"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "muse"
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - musenet
  server:
    image: immanewbies/muse-server:latest
    environment:
      PORT: "8081"
      SALT: "10"
      EC2_IPV4: "http://13.251.17.140:3000"
      DB_HOST: localhost
      DB_USER: "new"
      DB_PWD: "123"
      DB_DB: "muse"
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    networks:
      - musenet
  client:
    image: immanewbies/muse-react:latest
    environment:
      REACT_APP_EC2_API: "http://13.251.17.140:8081" 
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - musenet

networks:
  musenet:
