version: '3.9'
services:
  db:
    # build: ../database
    image: immanewbies/muse-mysql:latest
    container_name: muse-mysql
    environment:
      MYSQL_USER: new
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: muse
    ports:
      - "3306:3306"
    restart: always
    networks:
      - muse 
  server:
    # build: ../server
    image: immanewbies/muse-server:latest
    container_name: muse-server
    environment:
      PORT: 8081
      SALT: 10
      EC2_IPV4: client
      MYSQL_HOST: db
      MYSQL_USER: new
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: muse
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    networks:
      - muse
  client:
    # build: ../client
    image: immanewbies/muse-react:latest
    container_name: muse-client
    environment:
      REACT_APP_EC2_API: server
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: on-failure
    networks:
      - muse

networks:
  muse:
    driver: bridge