version: '3.9'
services:
  db:
    build: ../database
    container_name: muse-mysql
    environment:
      MYSQL_USER: new
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: muse
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - muse_db_data:/var/lib/mysql
    networks:
      - muse 
  server:
    build: ../server
    container_name: muse-server
    environment:
      PORT: 8081
      SALT: 10
      EC2_IPV4: client
      MYSQL_HOST: db
      MYSQL_USER: new
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: muse
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    networks:
      - muse
  client:
    build: ../client
    container_name: muse-client
    environment:
      REACT_APP_EC2_API: server
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: on-failure
    networks:
      - muse

volumes:
  muse_db_data:
    driver: local

networks:
  muse:
    driver: bridge