version: '3.8'
services:
  db:
    image: immanewbies/muse-mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_USER: new
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: muse
    ports:
      - "3306:3306"
    volumes:
      - ./database/muse.sql:/docker-entrypoint-initdb.d/
    restart: on-failure
    networks:
      - musenet
  server:
    image: immanewbies/muse-server:latest
    environment:
      PORT: 8081
      SALT: 10
      EC2_IPV4: 3.1.174.146:3000
      DB_HOST: db
      DB_USER: new
      DB_PWD: 123
      DB_DB: muse
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    networks:
      - musenet
  client:
    image: immanewbies/muse-react:latest
    environment:
      EC2_API: 3.1.174.146:8081
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: on-failure
    networks:
      - musenet

networks:
  musenet:
